# Default values for azure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# location: eastus
# resourceGroupName: control-plane
azuread: {}
tags: {}
network:
  addressSpace:
    - 10.0.0.0/16
  subnets:
    - name: k8s
      addressPrefixes:
        - 10.0.1.0/24
      serviceEndpoints:
        - Microsoft.ContainerRegistry
        - Microsoft.EventHub
        - Microsoft.KeyVault
        - Microsoft.ServiceBus
        - Microsoft.Storage
    - name: privatelinks
      addressPrefixes:
        - 10.0.0.0/25
    - name: application-gateway
      addressPrefixes:
        - 10.0.0.128/25
kubernetes:
  defaultNodePool:
    minCount: 1
    maxCount: 6
    onlyCriticalAddonsEnabled: true
    osDiskType: Ephemeral
    osDiskSizeGb: 70
    vmSize: Standard_D2ads_v5
    nodeLabels:
      infra/computeClass: system
  networkProfile:
    dnsServiceIp: 10.0.4.10
    serviceCidr: 10.0.4.0/24
  skuTier: Free
  nodepools:
    - name: compute
      minCount: 0
      maxCount: 3
      osDiskType: Ephemeral
      osDiskSizeGb: 70
      vmSize: Standard_D2ads_v5
      nodeLabels:
        infra/computeClass: compute
      # nodeTaints:
    - name: localnvme
      minCount: 0
      maxCount: 3
      osDiskType: Ephemeral
      osDiskSizeGb: 70
      vmSize: Standard_L8s_v3
      nodeLabels:
        infra/computeClass: compute
        infra/storageClass: localnvme
      nodeTaints:
        - infra/storageClass=localnvme:NoSchedule
