{{- range .Values.kubernetes.nodepools }}
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  name: {{ include "azure.fullname" $ }}-{{ .name }}
  annotations:
    crossplane.io/external-name: {{ .name }}
  labels:
    {{- include "azure.labels" $ | nindent 4 }}
    app.kubernetes.io/component: azure-aks-nodepool-{{ .name }}
spec:
  forProvider:
    kubernetesClusterIdSelector:
      matchLabels:
        {{- include "azure.selectorLabels" $ | nindent 8 }}
    enableAutoScaling: true        
    maxCount: {{ .maxCount | default 3 }}
    minCount: {{ .minCount | default 0 }}
    # kubeletDiskType: Temporary
    osDiskType: {{ .osDiskType }}
    osDiskSizeGb: {{ .osDiskSizeGb }}
    vmSize: {{ .vmSize }}
    vnetSubnetIdSelector:
      matchLabels: 
        {{- include "azure.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: azure-subnet-k8s
    zones: ["1","2","3"] 
    {{- if .nodeLabels }}
    nodeLabels:
      {{- toYaml .nodeLabels | nindent 6 }}
    {{- end }}
    {{- with .nodeTaints }}
    nodeTaints:
      {{- toYaml . | nindent 6 }}
    {{- end }}        
    {{- with $.Values.tags }}
    tags:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---      
{{- end }}          