apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ include "azure.fullname" . }}-helm
spec:
  credentials:
    secretRef:
      # key: kubeconfig
      key: attribute.kube_admin_config_raw
      namespace: {{ .Release.Namespace }}
      name: {{ include "azure.fullname" . }}
    source: Secret